# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sect1',
            fields=[
                ('ts1_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('property_name', models.CharField(max_length=10000)),
                ('property_address', models.CharField(max_length=10000)),
                ('property_description', models.CharField(max_length=10000)),
                ('property_representative', models.CharField(max_length=10000)),
                ('pr_address', models.CharField(max_length=10000)),
                ('pr_phone', models.CharField(max_length=10)),
                ('pr_fax', models.CharField(max_length=10)),
                ('pr_email', models.EmailField(max_length=254)),
                ('authority_with_jurisdiction', models.CharField(max_length=10000)),
                ('aj_phone', models.CharField(max_length=10)),
                ('aj_fax', models.CharField(max_length=10)),
                ('aj_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sect2',
            fields=[
                ('ts2_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('org_test_service', models.CharField(max_length=10000)),
                ('ots_address', models.CharField(max_length=10000)),
                ('ots_phone', models.CharField(max_length=10)),
                ('ots_fax', models.CharField(max_length=10)),
                ('ots_email', models.EmailField(max_length=254)),
                ('service_technician', models.CharField(max_length=10000)),
                ('test_frequency', models.CharField(max_length=250)),
                ('monitor_org', models.CharField(max_length=10000)),
                ('mo_address', models.CharField(max_length=10000)),
                ('mo_phone', models.CharField(max_length=10)),
                ('mo_fax', models.CharField(max_length=10)),
                ('mo_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_number', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestDateTime',
            fields=[
                ('tdt_number', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(default=datetime.date)),
                ('inspection_time', models.TimeField(default=datetime.time)),
            ],
        ),
    ]
