# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('customer_pk', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('inspection_number', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(default=datetime.date.today)),
                ('inspection_time', models.TimeField(default=datetime.time(11, 15, 4, 955622))),
                ('property_name', models.CharField(max_length=10000)),
                ('property_address', models.CharField(max_length=10000)),
                ('property_description', models.CharField(max_length=10000)),
                ('property_representative', models.CharField(max_length=10000)),
                ('pr_address', models.CharField(max_length=10000)),
                ('pr_phone', models.CharField(max_length=10)),
                ('pr_fax', models.CharField(max_length=10)),
                ('pr_email', models.EmailField(max_length=254)),
                ('authority_with_jurisdiction', models.CharField(max_length=10000)),
                ('aj_phone', models.CharField(max_length=10)),
                ('aj_fax', models.CharField(max_length=10)),
                ('aj_email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_forms.CustomerAddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('inspection_number', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(default=datetime.date.today)),
                ('inspection_time', models.TimeField(default=datetime.time(11, 15, 4, 955622))),
                ('org_test_service', models.CharField(max_length=10000)),
                ('ots_address', models.CharField(max_length=10000)),
                ('ots_phone', models.CharField(max_length=10)),
                ('ots_fax', models.CharField(max_length=10)),
                ('ots_email', models.EmailField(max_length=254)),
                ('service_technician', models.CharField(max_length=10000)),
                ('test_frequency', models.CharField(max_length=250)),
                ('monitor_org', models.CharField(max_length=10000)),
                ('mo_address', models.CharField(max_length=10000)),
                ('mo_phone', models.CharField(max_length=10)),
                ('mo_fax', models.CharField(max_length=10)),
                ('mo_email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_forms.CustomerAddress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
