# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_forms.TestDateTime'),
        ),
    ]
