# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_time',
            field=models.TimeField(default=datetime.time(10, 45, 51, 96211)),
        ),
        migrations.AlterField(
            model_name='section7_8',
            name='device_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section7_8',
            name='device_inspection_cycle',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section7_8',
            name='device_inspection_type',
            field=models.CharField(blank=True, choices=[('V', 'Visual Inspection'), ('F', 'Functional Test')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='section7_8',
            name='device_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='section7_8',
            name='device_test_results',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section7_8',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
