# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0002_test_tdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tdt',
        ),
    ]
