# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0005_auto_20170808_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='address',
        ),
    ]
