# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_forms', '0006_remove_test_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTest',
            fields=[
                ('test_number', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=10000)),
                ('sect1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_forms.Sect1')),
                ('sect2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_forms.Sect2')),
                ('tdt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_forms.TestDateTime')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='sect1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sect2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tdt',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
