from django.contrib import admin

from . import models

admin.site.register(models.CustomerAddress)
admin.site.register(models.Inspection)
admin.site.register(models.Section1)
admin.site.register(models.Section2)
admin.site.register(models.Section3)
admin.site.register(models.Section4_1)
admin.site.register(models.Section4_2)
admin.site.register(models.Section5)
admin.site.register(models.Section6)
admin.site.register(models.Section7_1)
admin.site.register(models.Section7_2)
admin.site.register(models.Section7_3)
admin.site.register(models.Section7_4)
admin.site.register(models.Section7_5)
admin.site.register(models.Section7_6)
admin.site.register(models.Section7_7)
admin.site.register(models.Section7_8)
admin.site.register(models.Section7_9)
admin.site.register(models.Section8)
admin.site.register(models.Section9)
admin.site.register(models.Section10_1)
admin.site.register(models.Section10_2)
